#!/bin/sh

### BEGIN INIT INFO
# Provides:          ftpserver-python
# Required-Start:    $network $syslog
# Required-Stop:     $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Run the simple python-based FTP server
### END INIT INFO

python /home/robot/ftpserver.py
